<?php
require_once ( ADVISOR_CORE . 'shortcodes/advisor-text-video-image.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-benefits-carousel.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-fun-facts-counter.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-default-slider.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-testimonials.php' ) ;
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-slogan.php' ) ;
require_once ( ADVISOR_CORE . 'shortcodes/advisor-revolution-slider.php' ) ;
require_once ( ADVISOR_CORE . 'shortcodes/advisor-our-team-carousel.php' ) ;
require_once ( ADVISOR_CORE . 'shortcodes/advisor-text-button.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-grid.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-carousel-icons.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-grid-icons.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-contact.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-accordion-tab-images.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-gallery.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-case-studies.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-company-history.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-our-partners.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-tabs.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-charts.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-our-team-grid.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-contact-us.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-contact-us-map.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-contact-multiple-maps.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-right-heading-text-left.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-google-chart.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-intro.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-carousel.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-company-history-progressbar.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-our-partners-grid.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-latest-news.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-subscription.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-slogan-icons.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-services-carousel-icons-with-heading.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-full-width-bannar.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-strategy-graph-with-grid-icons.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-price-plan.php' );
require_once ( ADVISOR_CORE . 'shortcodes/advisor-investment-plan.php' );
?>
